"""CMS NH_ProviderInfo_* → ProviderInfoNorm_* column map.

Verified from: NH_ProviderInfo_Apr2026.csv vs ProviderInfoNorm_2026_04.csv (numeric/string
match on 14,150+ CCNs). Includes nursing_case_mix_index / ratio mappings required for CMI.
"""

from __future__ import annotations

NH_TO_NORM: dict[str, str] = {
    "ccn": "CMS Certification Number (CCN)",
    "provider_name": "Provider Name",
    "state": "State",
    "city": "City/Town",
    "county": "County/Parish",
    "ownership_type": "Ownership Type",
    "avg_residents_per_day": "Average Number of Residents per Day",
    "overall_rating": "Overall Rating",
    "reported_na_hrs_per_resident_per_day": "Reported Nurse Aide Staffing Hours per Resident per Day",
    "reported_lpn_hrs_per_resident_per_day": "Reported LPN Staffing Hours per Resident per Day",
    "reported_rn_hrs_per_resident_per_day": "Reported RN Staffing Hours per Resident per Day",
    "reported_licensed_hrs_per_resident_per_day": "Reported Licensed Staffing Hours per Resident per Day",
    "reported_total_nurse_hrs_per_resident_per_day": "Reported Total Nurse Staffing Hours per Resident per Day",
    "weekend_total_nurse_hrs_per_resident_per_day": "Total number of nurse staff hours per resident per day on the weekend",
    "weekend_rn_hrs_per_resident_per_day": "Registered Nurse hours per resident per day on the weekend",
    "reported_pt_hrs_per_resident_per_day": "Reported Physical Therapist Staffing Hours per Resident Per Day",
    "case_mix_na_hrs_per_resident_per_day": "Case-Mix Nurse Aide Staffing Hours per Resident per Day",
    "case_mix_lpn_hrs_per_resident_per_day": "Case-Mix LPN Staffing Hours per Resident per Day",
    "case_mix_rn_hrs_per_resident_per_day": "Case-Mix RN Staffing Hours per Resident per Day",
    "case_mix_total_nurse_hrs_per_resident_per_day": "Case-Mix Total Nurse Staffing Hours per Resident per Day",
    "case_mix_weekend_total_nurse_hrs_per_resident_per_day": "Case-Mix Weekend Total Nurse Staffing Hours per Resident per Day",
    "adjusted_na_hrs_per_resident_per_day": "Adjusted Nurse Aide Staffing Hours per Resident per Day",
    "adjusted_lpn_hrs_per_resident_per_day": "Adjusted LPN Staffing Hours per Resident per Day",
    "adjusted_rn_hrs_per_resident_per_day": "Adjusted RN Staffing Hours per Resident per Day",
    "adjusted_total_nurse_hrs_per_resident_per_day": "Adjusted Total Nurse Staffing Hours per Resident per Day",
    "adjusted_weekend_total_nurse_hrs_per_resident_per_day": "Adjusted Weekend Total Nurse Staffing Hours per Resident per Day",
    "nursing_case_mix_index": "Nursing Case-Mix Index",
    "nursing_case_mix_index_ratio": "Nursing Case-Mix Index Ratio",
    "processing_date": "Processing Date",
    "staffing_rating": "Staffing Rating",
    "health_inspection_rating": "Health Inspection Rating",
    "total_nursing_staff_turnover": "Total nursing staff turnover",
    "registered_nurse_turnover": "Registered Nurse turnover",
    "provider_changed_ownership_in_last_12_months": "Provider Changed Ownership in Last 12 Months",
    "affiliated_entity_name": "Chain Name",
    "affiliated_entity_id": "Chain ID",
    "chain_name": "Chain Name",
    "chain_id": "Chain ID",
    "fines": "Total Amount of Fines in Dollars",
    "penalties": "Total Number of Penalties",
    "sff_status": "Special Focus Status",
    "certified_beds": "Number of Certified Beds",
    "abuse_icon": "Abuse Icon",
    "provider_address": "Provider Address",
    "zip_code": "ZIP Code",
    "telephone": "Telephone Number",
    "ssa_county_code": "Provider SSA County Code",
    "urban": "Urban",
    "provider_type": "Provider Type",
    "resides_in_hospital": "Provider Resides in Hospital",
    "legal_business_name": "Legal Business Name",
    "date_first_approved": "Date First Approved to Provide Medicare and Medicaid Services",
    "chain_facility_count": "Number of Facilities in Chain",
    "chain_avg_overall_rating": "Chain Average Overall 5-star Rating",
    "chain_avg_health_rating": "Chain Average Health Inspection Rating",
    "chain_avg_staffing_rating": "Chain Average Staffing Rating",
    "chain_avg_qm_rating": "Chain Average QM Rating",
    "ccrc": "Continuing Care Retirement Community",
    "health_inspection_over_2_years": "Most Recent Health Inspection More Than 2 Years Ago",
    "resident_family_council": "With a Resident and Family Council",
    "automatic_sprinklers": "Automatic Sprinkler Systems in All Required Areas",
    "qm_rating": "QM Rating",
    "long_stay_qm_rating": "Long-Stay QM Rating",
    "short_stay_qm_rating": "Short-Stay QM Rating",
    "administrator_turnover": "Number of administrators who have left the nursing home",
    "cycle1_survey_date": "Rating Cycle 1 Standard Survey Health Date",
    "cycle1_total_deficiencies": "Rating Cycle 1 Total Number of Health Deficiencies",
    "cycle1_standard_deficiencies": "Rating Cycle 1 Number of Standard Health Deficiencies",
    "cycle1_complaint_deficiencies": "Rating Cycle 1 Number of Complaint Health Deficiencies",
    "cycle1_deficiency_score": "Rating Cycle 1 Health Deficiency Score",
    "cycle1_revisits": "Rating Cycle 1 Number of Health Revisits",
    "cycle1_revisit_score": "Rating Cycle 1 Health Revisit Score",
    "cycle1_total_health_score": "Rating Cycle 1 Total Health Score",
    "cycle2_survey_date": "Rating Cycle 2 Standard Health Survey Date",
    "cycle2_total_deficiencies": "Rating Cycle 2/3 Total Number of Health Deficiencies",
    "cycle2_standard_deficiencies": "Rating Cycle 2 Number of Standard Health Deficiencies",
    "cycle2_complaint_deficiencies": "Rating Cycle 2/3 Number of Complaint Health Deficiencies",
    "cycle2_deficiency_score": "Rating Cycle 2/3 Health Deficiency Score",
    "cycle2_revisits": "Rating Cycle 2/3 Number of Health Revisits",
    "cycle2_revisit_score": "Rating Cycle 2/3 Health Revisit Score",
    "cycle2_total_health_score": "Rating Cycle 2/3 Total Health Score",
    "total_weighted_health_score": "Total Weighted Health Survey Score",
    "infection_control_citations": "Number of Citations from Infection Control Inspections",
    "number_of_fines": "Number of Fines",
    "total_fines_dollars": "Total Amount of Fines in Dollars",
    "payment_denials": "Number of Payment Denials",
    "total_penalties": "Total Number of Penalties",
    "location": "Location",
    "latitude": "Latitude",
    "longitude": "Longitude",
    "geocoding_footnote": "Geocoding Footnote",
    "long_stay_qm_rating_footnote": "Long-Stay QM Rating Footnote",
    "short_stay_qm_rating_footnote": "Short-Stay QM Rating Footnote",
    "staffing_rating_footnote": "Staffing Rating Footnote",
}
