[theme]
primaryColor = "#1769aa"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[server]
headless = true
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = true
enableWebsocketCompression = true
favicon = "pbj_favicon.png"