[theme]
primaryColor = "#1769aa"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[server]
headless = true
address = "localhost"
enableCORS = true
enableXsrfProtection = true
enableWebsocketCompression = true